use final;
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (37, 14, 'Counterfeit item', 'Resolved', '2024-09-17');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (17, 16, 'Counterfeit item', 'Under Review', '2025-01-27');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (27, 25, 'Counterfeit item', 'Dismissed', '2024-11-03');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (49, 2, 'suspicious activity', 'Under Review', '2024-10-17');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (14, 26, 'Misleading description', 'Resolved', '2025-02-27');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (3, 14, 'scam attempt', 'Dismissed', '2024-09-03');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (19, 10, 'Counterfeit item', 'Dismissed', '2024-10-31');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (20, 24, 'Counterfeit item', 'Under Review', '2025-01-25');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (29, 28, 'other', 'Dismissed', '2025-03-02');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (9, 21, 'other', 'Under Review', '2024-09-18');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (9, 5, 'other', 'Dismissed', '2024-04-29');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (12, 26, 'Misleading description', 'Resolved', '2024-06-17');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (24, 7, 'other', 'Under Review', '2025-01-28');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (18, 23, 'Counterfeit item', 'Dismissed', '2024-06-30');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (21, 30, 'Item not as described', 'Dismissed', '2024-05-24');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (7, 20, 'other', 'Resolved', '2024-10-22');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (46, 26, 'other', 'Dismissed', '2024-09-17');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (21, 6, 'scam attempt', 'Dismissed', '2024-08-06');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (46, 5, 'Counterfeit item', 'Resolved', '2024-09-16');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (34, 22, 'suspicious activity', 'Dismissed', '2024-07-22');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (18, 10, 'Misleading description', 'Under Review', '2024-09-10');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (5, 27, 'Item not as described', 'Resolved', '2025-03-20');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (23, 21, 'Item not as described', 'Dismissed', '2024-06-10');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (9, 22, 'Counterfeit item', 'Resolved', '2025-04-01');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (48, 22, 'scam attempt', 'Dismissed', '2024-05-02');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (5, 20, 'Misleading description', 'Dismissed', '2024-07-21');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (33, 22, 'Counterfeit item', 'Dismissed', '2025-02-03');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (1, 26, 'Counterfeit item', 'Under Review', '2024-06-01');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (5, 12, 'Misleading description', 'Resolved', '2024-07-09');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (44, 26, 'suspicious activity', 'Dismissed', '2025-02-12');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (39, 27, 'Item not as described', 'Resolved', '2024-07-25');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (32, 5, 'scam attempt', 'Dismissed', '2024-07-20');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (22, 18, 'Item not as described', 'Resolved', '2025-01-10');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (5, 8, 'other', 'Dismissed', '2024-08-12');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (22, 26, 'scam attempt', 'Dismissed', '2025-02-18');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (29, 13, 'Misleading description', 'Under Review', '2024-09-30');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (44, 19, 'suspicious activity', 'Under Review', '2024-09-11');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (44, 4, 'Item not as described', 'Resolved', '2024-06-17');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (34, 7, 'suspicious activity', 'Dismissed', '2024-09-14');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (6, 3, 'scam attempt', 'Resolved', '2024-08-07');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (25, 29, 'suspicious activity', 'Dismissed', '2024-11-29');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (43, 13, 'Misleading description', 'Dismissed', '2024-10-20');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (21, 28, 'other', 'Under Review', '2025-01-13');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (14, 6, 'Item not as described', 'Under Review', '2024-06-28');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (43, 5, 'other', 'Dismissed', '2024-11-29');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (20, 23, 'suspicious activity', 'Dismissed', '2024-11-29');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (24, 25, 'other', 'Under Review', '2024-08-04');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (36, 3, 'Item not as described', 'Under Review', '2024-11-14');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (6, 4, 'Item not as described', 'Dismissed', '2024-12-03');
insert into Fraud_Reports (trade_id, reported_by, reason, status, created_at) values (45, 29, 'Misleading description', 'Resolved', '2024-09-06');