insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (1, 'Thekla', 'Dillinton', 'Democrat', 'Female', 38, 'Post Graduate', 'Georgia');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (2, 'Brit', 'Hallard', 'Democrat', 'Female', 42, 'No Education', 'New York');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (3, 'Benoite', 'Tattersall', 'Republican', 'Female', 46, 'High School', 'New York');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (4, 'Riobard', 'Barroux', 'Republican', 'Male', 75, 'College', 'Indiana');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (5, 'Aggi', 'Krolak', 'Republican', 'Female', 65, 'No Education', 'Pennsylvania');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (6, 'Sanderson', 'Moens', 'Independent', 'Male', 48, 'Post Graduate', 'Indiana');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (7, 'Vasili', 'Guerro', 'Republican', 'Male', 40, 'No Education', 'Washington');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (8, 'Giordano', 'Mowatt', 'Republican', 'Male', 78, 'Post Graduate', 'Kansas');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (9, 'Lauralee', 'Caslake', 'Independent', 'Female', 45, 'No Education', 'Texas');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (10, 'Hendrik', 'Metzke', 'Independent', 'Male', 56, 'High School', 'Florida');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (11, 'Erin', 'Birdsall', 'Republican', 'Male', 69, 'College', 'Texas');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (12, 'Townsend', 'Skechley', 'Republican', 'Male', 47, 'Post Graduate', 'Delaware');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (13, 'Beryle', 'Acutt', 'Independent', 'Female', 86, 'No Education', 'California');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (14, 'Chevy', 'Pennetti', 'Republican', 'Male', 61, 'No Education', 'Florida');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (15, 'Shawn', 'Aldin', 'Independent', 'Female', 66, 'College', 'Florida');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (16, 'Rosabelle', 'Ponnsett', 'Republican', 'Female', 64, 'No Education', 'Georgia');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (17, 'Berk', 'Gostage', 'Democrat', 'Male', 64, 'High School', 'New Mexico');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (18, 'Wanda', 'Livard', 'Republican', 'Female', 39, 'No Education', 'North Carolina');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (19, 'Hedvig', 'Denisovich', 'Republican', 'Female', 35, 'Post Graduate', 'New York');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (20, 'Dominik', 'Skylett', 'Independent', 'Male', 62, 'High School', 'Texas');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (21, 'Debby', 'McWilliams', 'Independent', 'Female', 64, 'College', 'Texas');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (22, 'Gussie', 'Fillon', 'Independent', 'Female', 51, 'Post Graduate', 'California');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (23, 'Marshall', 'Darcey', 'Democrat', 'Male', 81, 'High School', 'Arizona');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (24, 'Oliy', 'Yusupov', 'Republican', 'Female', 93, 'No Education', 'Pennsylvania');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (25, 'Cordy', 'Canaan', 'Independent', 'Female', 42, 'College', 'Texas');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (26, 'Donielle', 'Hassall', 'Independent', 'Female', 86, 'Post Graduate', 'California');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (27, 'Arlen', 'Cantu', 'Independent', 'Male', 58, 'High School', 'District of Columbia');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (28, 'Grissel', 'Gruszecki', 'Republican', 'Female', 94, 'High School', 'Florida');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (29, 'Marnia', 'Ible', 'Republican', 'Female', 70, 'High School', 'Maryland');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (30, 'Weylin', 'Cock', 'Democrat', 'Male', 72, 'College', 'Florida');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (31, 'Gaven', 'Vivers', 'Democrat', 'Male', 43, 'Post Graduate', 'Pennsylvania');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (32, 'Gussie', 'Farries', 'Independent', 'Female', 84, 'Post Graduate', 'Texas');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (33, 'Ellynn', 'Sweet', 'Republican', 'Female', 92, 'Post Graduate', 'Texas');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (34, 'Rafferty', 'Jenney', 'Independent', 'Male', 74, 'High School', 'Delaware');
insert into candidate (candidateId, firstName, lastName, politicalAffiliation, gender, age, educationLevel, homeState) values (35, 'Abra', 'Mallatratt', 'Democrat', 'Female', 82, 'Post Graduate', 'Virginia');

insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (1, 1998, '7', 271, 448);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (2, 2012, '22', 248, 287);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (3, 2007, '20', 51, 293);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (4, 2010, '21', 475, 204);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (5, 2002, '18', 193, 237);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (6, 2009, '30', 422, 360);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (7, 1992, '23', 336, 273);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (8, 2003, '14', 193, 241);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (9, 2004, '26', 290, 338);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (10, 2004, '16', 11, 508);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (11, 2012, '11', 464, 142);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (12, 2004, '9', 139, 91);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (13, 1987, '34', 448, 322);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (14, 1994, '27', 312, 165);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (15, 1986, '5', 129, 344);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (16, 1992, '31', 66, 258);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (17, 2005, '35', 179, 191);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (18, 2000, '12', 508, 236);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (19, 1991, '15', 510, 289);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (20, 2012, '1', 204, 506);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (21, 2011, '6', 300, 38);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (22, 1991, '10', 518, 143);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (23, 1999, '33', 150, 321);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (24, 1992, '28', 328, 152);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (25, 1989, '3', 314, 507);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (26, 1985, '19', 207, 49);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (27, 2004, '17', 121, 141);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (28, 1969, '32', 221, 385);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (29, 1999, '4', 300, 196);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (30, 2002, '13', 521, 20);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (31, 2007, '2', 39, 360);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (32, 2005, '29', 90, 110);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (33, 2005, '8', 394, 338);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (34, 2003, '25', 137, 265);
insert into election (electionId, year, winnerId, electoralVoteDifference, popularVoteDifference) values (35, 1988, '24', 75, 154);



insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('18', 1, 'taxi cab', '$3164.91', 5537);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('26', 2, 'magazine ad', '$9866.00', 1284);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('35', 3, 'magazine ad', '$4022.32', 6072);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('2', 4, 'movie theater', '$1946.25', 6283);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('25', 5, 'social media', '$7580.59', 9519);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('16', 6, 'gas station', '$44.27', 2780);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('15', 7, 'elevator', '$3997.79', 1026);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('3', 8, 'airport', '$5013.21', 7831);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('28', 9, 'magazine ad', '$2947.15', 8180);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('10', 10, 'taxi cab', '$5737.74', 6782);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('23', 11, 'bus shelter', '$4759.53', 8284);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('32', 12, 'billboard', '$2052.27', 6744);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('13', 13, 'park bench', '$796.31', 3755);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('17', 14, 'elevator', '$1240.43', 1511);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('8', 15, 'radio commercial', '$8873.57', 8630);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('9', 16, 'subway station', '$3283.58', 6366);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('4', 17, 'subway station', '$4301.18', 3728);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('31', 18, 'shopping mall', '$3653.31', 3489);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('34', 19, 'sports stadium', '$5299.98', 3149);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('30', 20, 'park bench', '$8086.63', 3380);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('5', 21, 'website banner', '$2064.45', 9461);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('27', 22, 'subway station', '$7990.73', 2954);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('6', 23, 'airport', '$5919.53', 9750);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('22', 24, 'airport', '$9324.44', 8431);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('33', 25, 'radio commercial', '$4871.14', 5053);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('12', 26, 'social media', '$8524.59', 6600);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('21', 27, 'movie theater', '$9860.35', 1906);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('1', 28, 'online video platform', '$7872.19', 5330);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('14', 29, 'coffee shop', '$7726.53', 5947);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('29', 30, 'movie theater', '$893.64', 8306);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('19', 31, 'social media', '$9486.94', 8415);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('20', 32, 'sports stadium', '$9650.63', 6254);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('24', 33, 'taxi cab', '$7904.90', 5668);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('11', 34, 'coffee shop', '$5800.44', 3032);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('7', 35, 'street corner', '$2708.42', 3002);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('25', 36, 'elevator', '$9106.19', 3618);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('26', 37, 'subway station', '$3089.35', 3905);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('15', 38, 'radio commercial', '$1082.67', 3295);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('13', 39, 'gas station', '$542.83', 1046);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('22', 40, 'park bench', '$7500.29', 6551);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('19', 41, 'bus stop', '$9454.16', 7677);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('8', 42, 'coffee shop', '$5683.09', 871);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('31', 43, 'movie theater', '$5167.27', 5082);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('34', 44, 'coffee shop', '$4580.67', 2114);
insert into campaign (campaignId, advertisementId, location, cost, interactions) values ('10', 45, 'elevator', '$5314.93', 8824);
