# ------------------------------------------------------------
# Sample data for testing generated by ChatGPT
# ------------------------------------------------------------

sample_playlist_data = {
  "playlist": {
    "id": "37i9dQZF1DXcBWIGoYBM5M",
    "name": "Chill Hits",
    "description": "Relax and unwind with the latest chill hits.",
    "owner": {
      "id": "spotify_user_123",
      "display_name": "Spotify User"
    },
    "tracks": {
      "items": [
        {
          "track": {
            "id": "3n3Ppam7vgaVa1iaRUc9Lp",
            "name": "Lose Yourself",
            "artists": [
              {
                "id": "1dfeR4HaWDbWqFHLkxsg1d",
                "name": "Eminem"
              }
            ],
            "album": {
              "id": "1ATL5GLyefJaxhQzSPVrLX",
              "name": "8 Mile"
            },
            "duration_ms": 326000,
            "track_number": 1,
            "disc_number": 1,
            "preview_url": "https://p.scdn.co/mp3-preview/lose-yourself.mp3",
            "uri": "spotify:track:3n3Ppam7vgaVa1iaRUc9Lp"
          }
        },
        {
          "track": {
            "id": "7ouMYWpwJ422jRcDASZB7P",
            "name": "Blinding Lights",
            "artists": [
              {
                "id": "0fW8E0XdT6aG9aFh6jGpYo",
                "name": "The Weeknd"
              }
            ],
            "album": {
              "id": "1ATL5GLyefJaxhQzSPVrLX",
              "name": "After Hours"
            },
            "duration_ms": 200040,
            "track_number": 9,
            "disc_number": 1,
            "preview_url": "https://p.scdn.co/mp3-preview/blinding-lights.mp3",
            "uri": "spotify:track:7ouMYWpwJ422jRcDASZB7P"
          }
        },
        {
          "track": {
            "id": "4uLU6hMCjMI75M1A2tKUQC",
            "name": "Shape of You",
            "artists": [
              {
                "id": "6eUKZXaKkcviH0Ku9w2n3V",
                "name": "Ed Sheeran"
              }
            ],
            "album": {
              "id": "3fMbdgg4jU18AjLCKBhRSm",
              "name": "Divide"
            },
            "duration_ms": 233713,
            "track_number": 4,
            "disc_number": 1,
            "preview_url": "https://p.scdn.co/mp3-preview/shape-of-you.mp3",
            "uri": "spotify:track:4uLU6hMCjMI75M1A2tKUQC"
          }
        },
        {
          "track": {
            "id": "0VjIjW4GlUZAMYd2vXMi3b",
            "name": "Levitating",
            "artists": [
              {
                "id": "4tZwfgrHOc3mvqYlEYSvVi",
                "name": "Dua Lipa"
              }
            ],
            "album": {
              "id": "7dGJo4pcD2V6oG8kP0tJRR",
              "name": "Future Nostalgia"
            },
            "duration_ms": 203693,
            "track_number": 5,
            "disc_number": 1,
            "preview_url": "https://p.scdn.co/mp3-preview/levitating.mp3",
            "uri": "spotify:track:0VjIjW4GlUZAMYd2vXMi3b"
          }
        },
        {
          "track": {
            "id": "6habFhsOp2NvshLv26DqMb",
            "name": "Sunflower",
            "artists": [
              {
                "id": "1dfeR4HaWDbWqFHLkxsg1d",
                "name": "Post Malone"
              },
              {
                "id": "0C8ZW7ezQVs4URX5aX7Kqx",
                "name": "Swae Lee"
              }
            ],
            "album": {
              "id": "6k3hyp4efgfHP5GMVd3Agw",
              "name": "Spider-Man: Into the Spider-Verse (Soundtrack)"
            },
            "duration_ms": 158000,
            "track_number": 3,
            "disc_number": 1,
            "preview_url": "https://p.scdn.co/mp3-preview/sunflower.mp3",
            "uri": "spotify:track:6habFhsOp2NvshLv26DqMb"
          }
        }
      ]
    },
    "uri": "spotify:playlist:37i9dQZF1DXcBWIGoYBM5M"
  }
}